# Dockercomposeはコンテナをどのように起動するかを書く

# Dockercomposeのファイル書きますよ宣言
version: '3'

services:
  # コンテナ毎にserviceの下にネストして書く
  web:
    # カレントディレクトリーにあるDockerfileをbuildする
    build: .
    # pabulishするポートを書く。
    ports:
      - '3000:3000'
    # マウントするディレクトリを指定する
    volumes:
      - '.:/docker-app'
    tty: true
    stdin_open: true
